In [1]:
import numpy as np

princess_count = 3

# 顺手就用整数了
w1 = np.array([100,99,97])
w2 = np.array([5,4,1])
w3 = np.array([10,7,3])

#                   公主1         公主2      公主3
# 王子1 彩礼        100           99         97
# 王子2 彩礼         5            4          1
# 王子3 彩礼        10            7          3

prices = np.vstack([w1,w2,w3])
print(np.ndim(prices))

n_a = np.linspace(1,100,25)
prices = n_a.reshape(5,5) # 也可用-1根据剩下的数计算，只要是方阵就好

def cal(x,y):
    return (x+1)*(y+1)

prices = np.fromfunction(cal,(9,9))

2


In [2]:
achieve = 0
# 循环 princess_count 次，取出 princess_count 个数相加

# 假设同一个王子不会给多个公主相同的彩礼
def get_largest(prices):
    row_index = -1
    col_index = -1
    l_range = -1
    result = 0,row_index,col_index
    
    for one in prices:
        print(one)
        row_index += 1
        col_index = np.argmax(one)
        o_range = np.ptp(one) # 求极差
        if(l_range < o_range):
            l_range = o_range
            result = one[col_index],row_index,col_index
    # print(result)
    return result

def get_range(prices, achieve):
    largest,row_index,col_index = get_largest(prices)
    achieve += largest
    print(achieve)
    cofactor = np.delete(prices,row_index,axis = 0)
    cofactor = np.delete(cofactor,col_index,axis = 1)
    print(cofactor)
    print(np.size(cofactor))
    
    if(np.size(cofactor) == 0):
        return achieve
    else:
        return get_range(cofactor, achieve)

In [3]:
achieve = get_range(prices, achieve)
print(achieve)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
[ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
[ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
[ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
[ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
[ 9. 18. 27. 36. 45. 54. 63. 72. 81.]
81.0
[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 2.  4.  6.  8. 10. 12. 14. 16.]
 [ 3.  6.  9. 12. 15. 18. 21. 24.]
 [ 4.  8. 12. 16. 20. 24. 28. 32.]
 [ 5. 10. 15. 20. 25. 30. 35. 40.]
 [ 6. 12. 18. 24. 30. 36. 42. 48.]
 [ 7. 14. 21. 28. 35. 42. 49. 56.]
 [ 8. 16. 24. 32. 40. 48. 56. 64.]]
64
[1. 2. 3. 4. 5. 6. 7. 8.]
[ 2.  4.  6.  8. 10. 12. 14. 16.]
[ 3.  6.  9. 12. 15. 18. 21. 24.]
[ 4.  8. 12. 16. 20. 24. 28. 32.]
[ 5. 10. 15. 20. 25. 30. 35. 40.]
[ 6. 12. 18. 24. 30. 36. 42. 48.]
[ 7. 14. 21. 28. 35. 42. 49. 56.]
[ 8. 16. 24. 32. 40. 48. 56. 64.]
145.0
[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 1