In [1]:
import numpy as np

princess_count = 3

w1 = np.array([1,2,3])
w2 = np.array([2,3,4])
w3 = np.array([3,4,5])

#                   公主1         公主2      公主3
# 王子1 彩礼          1            2            3
# 王子2 彩礼          2            3            4
# 王子3 彩礼          3            4            5

prices = np.vstack([w1,w2,w3]) # np.transpose()

print(prices)
print(type(prices))

# 如果是一个元素一个元素输入，这工作可以在输入的时候做
# a,b,c = np.hsplit(prices,3)
# print(a)
# print("---------------------------a")
# print(b)
# print("---------------------------")
# print(c)

def get_largest(w_prices):
    index = -1
    ele = -1
    result = ele,index
    for one in w_prices:
        index += 1
        if(one > ele):
            ele = one
            result = ele,index
    return result

[[1 2 3]
 [2 3 4]
 [3 4 5]]
<class 'numpy.ndarray'>


In [2]:
princess_prices = np.hsplit(prices,princess_count) # 原矩阵纵向切片
y_index = -1 # 列索引
for price in princess_prices:
    y_index += 1
    y_largest,x_index = get_largest(price) # 某个公主获得的最大彩礼
    # print(x_index)
    # print(y_index)
    # print(y_largest)
    # print(price)
    
    # 余子式
    cofactor = np.delete(prices,x_index,axis = 0)
    cofactor = np.delete(cofactor,y_index,axis = 1)
    print(cofactor)


[3]
[[2 3]
 [3 4]]
[4]
[[1 3]
 [2 4]]
[5]
[[1 2]
 [2 3]]
