In [1]:
import numpy as np

princess_count = 3

# 顺手就用整数了
w1 = np.array([100,99,97])
w2 = np.array([5,4,1])
w3 = np.array([10,7,3])

#                   公主1         公主2      公主3
# 王子1 彩礼        100           99         97
# 王子2 彩礼         5            4          1
# 王子3 彩礼        10            7          3

prices = np.vstack([w1,w2,w3])
print(np.ndim(prices))

a11 = np.linspace(1,100,25)
prices = a11.reshape(5,-1)

achieve = 0
# 循环 princess_count 次，取出 princess_count 个数相加

# 假设同一个王子不会给多个公主相同的彩礼
def get_largest(prices):
    row_index = -1
    col_index = -1
    l_range = -1
    result = 0,row_index,col_index
    
    for one in prices:
        print(one)
        row_index += 1
        col_index = np.argmax(one)
        o_range = np.ptp(one) # 求极差
        if(l_range < o_range):
            l_range = o_range
            result = one[col_index],row_index,col_index
    # print(result)
    return result

def get_range(prices, achieve):
    largest,row_index,col_index = get_largest(prices)
    achieve += largest
    print(achieve)
    cofactor = np.delete(prices,row_index,axis = 0)
    cofactor = np.delete(cofactor,col_index,axis = 1)
    print(cofactor)
    print(np.size(cofactor))
    
    if(np.size(cofactor) == 0):
        return achieve
    else:
        return get_range(cofactor, achieve)

achieve = get_range(prices, achieve)
print(achieve)

2
[ 1.     5.125  9.25  13.375 17.5  ]
[21.625 25.75  29.875 34.    38.125]
[42.25  46.375 50.5   54.625 58.75 ]
[62.875 67.    71.125 75.25  79.375]
[ 83.5    87.625  91.75   95.875 100.   ]
17.5
[[21.625 25.75  29.875 34.   ]
 [42.25  46.375 50.5   54.625]
 [62.875 67.    71.125 75.25 ]
 [83.5   87.625 91.75  95.875]]
16
[21.625 25.75  29.875 34.   ]
[42.25  46.375 50.5   54.625]
[62.875 67.    71.125 75.25 ]
[83.5   87.625 91.75  95.875]
51.5
[[42.25  46.375 50.5  ]
 [62.875 67.    71.125]
 [83.5   87.625 91.75 ]]
9
[42.25  46.375 50.5  ]
[62.875 67.    71.125]
[83.5   87.625 91.75 ]
102.0
[[62.875 67.   ]
 [83.5   87.625]]
4
[62.875 67.   ]
[83.5   87.625]
169.0
[[83.5]]
1
[83.5]
252.5
[]
0
252.5
